name = 'schobert-microblog-theme'
license = 'MIT'
licenselink = 'https://github.com/stevenschobert/microblog-theme/LICENSE'
description = 'My custom theme for Micro.blog'
homepage = 'https://github.com/stevenschobert/microblog-theme'
demosite = 'https://stevenschobert.microblog.com'

[author]
  name = 'Steven Schobert'
  homepage = 'https://stevenschobert.com'

[original]
  author = 'Herman Martinus'
  homepage = 'https://herman.bearblog.dev'
  repo = 'https://github.com/microdotblog/theme-bear'
